name: DexVault
slug: filmdex
icon: "mdi:movie-open"
version: "0.0.0-books-154-0f0dabe"
description: DexVault - Organize Your Collections
init: false
arch: 
  - aarch64
  - amd64
  - armv7
  - i386
image: "ghcr.io/renajohn/filmdex"
url: "https://github.com/renajohn/filmdex-ha-addon/tree/main/filmdex"
ingress: true
ingress_port: 3001
panel_icon: "mdi:movie-open"
panel_title: DexVault

options:
  log_level: info
  omdb_api_key: ""
  tmdb_api_key: ""
  max_upload_mb: 20

schema:
  log_level: list(debug|info|warn|error)
  omdb_api_key: password?
  tmdb_api_key: password?
  max_upload_mb: int
